# Generated by Django 6.0.5 on 2026-05-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('type_rdv', models.CharField(choices=[('consultation', 'Consultation'), ('coaching', 'Coaching'), ('formation', 'Formation'), ('soutien', 'Soutien concours'), ('autre', 'Autre')], default='consultation', max_length=20, verbose_name='Type de RDV')),
                ('date_souhaitee', models.DateTimeField(verbose_name='Date souhaitée')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message/Détails')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes_admin', models.TextField(blank=True, null=True, verbose_name='Notes administrateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_souhaitee'],
            },
        ),
    ]
