# Generated by Django 6.0.3 on 2026-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Couleur principale (format hex: #3B82F6)', max_length=7, verbose_name='Couleur principale')),
                ('secondary_color', models.CharField(default='#8B5CF6', help_text='Couleur secondaire (format hex: #8B5CF6)', max_length=7, verbose_name='Couleur secondaire')),
                ('accent_color', models.CharField(default='#F59E0B', help_text="Couleur d'accentuation (format hex: #F59E0B)", max_length=7, verbose_name="Couleur d'accentuation")),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Couleur de fond (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur de fond')),
                ('text_color', models.CharField(default='#1F2937', help_text='Couleur du texte (format hex: #1F2937)', max_length=7, verbose_name='Couleur du texte')),
                ('hero_title', models.CharField(default='Bienvenue chez Abou Bah Consulting', max_length=200, verbose_name='Titre principal (Hero)')),
                ('hero_subtitle', models.TextField(default='Cabinet de consultation pédagogique spécialisé dans la formation et le coaching', max_length=500, verbose_name='Sous-titre (Hero)')),
                ('hero_background_image', models.ImageField(blank=True, null=True, upload_to='customization/hero/', verbose_name='Image de fond Hero')),
                ('hero_button_text', models.CharField(default='Prendre rendez-vous', max_length=100, verbose_name='Texte du bouton Hero')),
                ('hero_button_link', models.CharField(default='/contact', max_length=200, verbose_name='Lien du bouton Hero')),
                ('about_title', models.CharField(default='À propos de nous', max_length=200, verbose_name='Titre section À propos')),
                ('about_description', models.TextField(default="Abou Bah Consulting est un cabinet de consultation pédagogique dédié à l'excellence éducative.", verbose_name='Description section À propos')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='customization/about/', verbose_name='Image section À propos')),
                ('show_partners_section', models.BooleanField(default=True, verbose_name='Afficher la section Partenaires')),
                ('show_testimonials_section', models.BooleanField(default=True, verbose_name='Afficher la section Témoignages')),
                ('show_blog_section', models.BooleanField(default=True, verbose_name="Afficher la section Blog sur la page d'accueil")),
                ('items_per_page', models.PositiveIntegerField(default=6, help_text="Nombre d'éléments à afficher par page (services, articles, etc.)", verbose_name='Éléments par page')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='URL Facebook')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='URL Twitter/X')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='URL LinkedIn')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='URL Instagram')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='URL YouTube')),
                ('contact_email', models.EmailField(default='contact@aboubah-consulting.com', max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(default='+223 XX XX XX XX', max_length=20, verbose_name='Téléphone de contact')),
                ('contact_address', models.TextField(default='Bamako, Mali', verbose_name='Adresse physique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Configuration active')),
            ],
            options={
                'verbose_name': 'Personnalisation du site',
                'verbose_name_plural': 'Personnalisation du site',
                'ordering': ['-created_at'],
            },
        ),
    ]
