# Generated by Django 6.0.3 on 2026-05-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_1_title',
            field=models.CharField(default='Positionnement', max_length=100, verbose_name='Titre Carte 1'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_1_value',
            field=models.CharField(default='Pragmatique & exigeant', max_length=100, verbose_name='Valeur Carte 1'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_2_title',
            field=models.CharField(default='Public', max_length=100, verbose_name='Titre Carte 2'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_2_value',
            field=models.CharField(default='Particuliers & organisations', max_length=100, verbose_name='Valeur Carte 2'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_3_title',
            field=models.CharField(default='Format', max_length=100, verbose_name='Titre Carte 3'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_3_value',
            field=models.CharField(default='Sur mesure', max_length=100, verbose_name='Valeur Carte 3'),
        ),
    ]
