# Generated by Django 6.0.3 on 2026-05-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_sitecustomization_hero_card_1_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='services_description',
            field=models.TextField(default="Chaque prestation combine méthode, clarté et mise en pratique. L'objectif est simple: renforcer vos compétences et rendre vos livrables irréprochables.", max_length=500, verbose_name='Description section Services'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='services_title',
            field=models.CharField(default='Des services conçus pour produire un vrai changement', max_length=200, verbose_name='Titre section Services'),
        ),
    ]
