# Generated by Django 6.0.3 on 2026-05-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_sitecustomization_services_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du slide')),
                ('subtitle', models.CharField(max_length=500, verbose_name='Sous-titre du slide')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Image du slide')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)", verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='show_slideshow',
            field=models.BooleanField(default=True, verbose_name='Afficher le diaporama'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='slideshow_autoplay_delay',
            field=models.PositiveIntegerField(default=3500, help_text='Délai entre les slides en millisecondes', verbose_name='Délai autoplay (ms)'),
        ),
    ]
