# Generated by Django 6.0.3 on 2026-05-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0005_sitecustomization_slideshow_image_fit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecustomization',
            name='slideshow_image_fit',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='slideshow_overlay_opacity',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='slideshow_title_position',
        ),
        migrations.AddField(
            model_name='slide',
            name='image_fit',
            field=models.CharField(choices=[('contain', 'Contenir (sans déformer)'), ('cover', 'Couvrir (remplir)'), ('fill', 'Remplir (étirer)')], default='contain', max_length=20, verbose_name="Mode d'affichage de l'image"),
        ),
        migrations.AddField(
            model_name='slide',
            name='overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.7, help_text="Opacité du fond sombre sur l'image (0.0 à 1.0)", max_digits=3, verbose_name='Opacité overlay'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_position',
            field=models.CharField(choices=[('top-left', 'Haut Gauche'), ('top-center', 'Haut Centre'), ('top-right', 'Haut Droite'), ('center-left', 'Centre Gauche'), ('center', 'Centre'), ('center-right', 'Centre Droite'), ('bottom-left', 'Bas Gauche'), ('bottom-center', 'Bas Centre'), ('bottom-right', 'Bas Droite')], default='center', max_length=20, verbose_name='Position du titre'),
        ),
    ]
