# Generated by Django 6.0.3 on 2026-05-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0006_remove_sitecustomization_slideshow_image_fit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_button_border_color',
            field=models.CharField(default='#1e3a5f', help_text='Couleur de bordure du bouton secondaire Hero (format hex: #1e3a5f)', max_length=7, verbose_name='Couleur bordure bouton secondaire Hero'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_button_primary_color',
            field=models.CharField(default='#1e3a5f', help_text='Couleur de fond du bouton principal Hero (format hex: #1e3a5f)', max_length=7, verbose_name='Couleur bouton principal Hero'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_button_primary_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur du texte du bouton principal Hero (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur texte bouton principal Hero'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_button_secondary_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond du bouton secondaire Hero (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur bouton secondaire Hero'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_button_secondary_text_color',
            field=models.CharField(default='#1e3a5f', help_text='Couleur du texte du bouton secondaire Hero (format hex: #1e3a5f)', max_length=7, verbose_name='Couleur texte bouton secondaire Hero'),
        ),
    ]
