# Generated by Django 6.0.3 on 2026-05-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0007_sitecustomization_hero_button_border_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_badge_1_text',
            field=models.CharField(default='Conseil • Formation • Coaching', max_length=100, verbose_name='Texte Badge 1'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_badge_2_text',
            field=models.CharField(default='Méthode • Rigueur • Impact', max_length=100, verbose_name='Texte Badge 2'),
        ),
    ]
