# Generated by Django 6.0.3 on 2026-05-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0008_sitecustomization_hero_badge_1_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_badge_primary_color',
            field=models.CharField(default='#F59E0B', help_text='Couleur de fond du badge primaire Hero (format hex: #F59E0B)', max_length=7, verbose_name='Couleur fond badge 1'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_badge_primary_text_color',
            field=models.CharField(default='#1F2937', help_text='Couleur du texte du badge primaire Hero (format hex: #1F2937)', max_length=7, verbose_name='Couleur texte badge 1'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_badge_secondary_text_color',
            field=models.CharField(default='#1F2937', help_text='Couleur du texte du badge secondaire Hero (format hex: #1F2937)', max_length=7, verbose_name='Couleur texte badge 2'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond des cartes Hero (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur fond cartes'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_border_color',
            field=models.CharField(default='#3B82F6', help_text='Couleur de bordure des cartes Hero (format hex: #3B82F6)', max_length=7, verbose_name='Couleur bordure cartes'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_title_color',
            field=models.CharField(default='#9CA3AF', help_text='Couleur des titres des cartes Hero (format hex: #9CA3AF)', max_length=7, verbose_name='Couleur titre cartes'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_value_color',
            field=models.CharField(default='#1F2937', help_text='Couleur des valeurs des cartes Hero (format hex: #1F2937)', max_length=7, verbose_name='Couleur valeur cartes'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_subtitle_color',
            field=models.CharField(default='#6B7280', help_text='Couleur du sous-titre Hero (format hex: #6B7280)', max_length=7, verbose_name='Couleur sous-titre Hero'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_title_color',
            field=models.CharField(default='#1F2937', help_text='Couleur du titre principal Hero (format hex: #1F2937)', max_length=7, verbose_name='Couleur titre Hero'),
        ),
    ]
