# Generated by Django 6.0.3 on 2026-05-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0009_sitecustomization_hero_badge_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_badge_primary_color',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_badge_primary_text_color',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_badge_secondary_text_color',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_button_border_color',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_button_primary_color',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_button_primary_text_color',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_button_secondary_color',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_button_secondary_text_color',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_card_background_color',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_card_border_color',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_card_title_color',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_card_value_color',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_subtitle_color',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='hero_title_color',
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='about_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration des couleurs de la section À propos en JSON', verbose_name='Couleurs À propos (JSON)'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration des couleurs de la section Hero en JSON', verbose_name='Couleurs Hero (JSON)'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='services_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration des couleurs de la section Services en JSON', verbose_name='Couleurs Services (JSON)'),
        ),
    ]
