# Generated by Django 6.0.3 on 2026-05-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0010_remove_sitecustomization_hero_badge_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='blog_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration des couleurs de la section Blog en JSON', verbose_name='Couleurs Blog (JSON)'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='blog_description',
            field=models.TextField(default='Consultez nos derniers articles et actualités', max_length=500, verbose_name='Description section Blog'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='blog_title',
            field=models.CharField(default='Derniers articles', max_length=200, verbose_name='Titre section Blog'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='cta_button_text',
            field=models.CharField(default='Contactez-nous', max_length=100, verbose_name='Texte bouton CTA'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='cta_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration des couleurs de la section CTA en JSON', verbose_name='Couleurs CTA (JSON)'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='cta_description',
            field=models.TextField(default="Contactez-nous dès aujourd'hui pour discuter de vos besoins", max_length=500, verbose_name='Description section CTA'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='cta_title',
            field=models.CharField(default='Prêt à démarrer ?', max_length=200, verbose_name='Titre section CTA'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='partners_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration des couleurs de la section Partenaires en JSON', verbose_name='Couleurs Partenaires (JSON)'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='partners_title',
            field=models.CharField(default='Nos partenaires', max_length=200, verbose_name='Titre section Partenaires'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='slideshow_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration des couleurs du diaporama en JSON', verbose_name='Couleurs Diaporama (JSON)'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='testimonials_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration des couleurs de la section Témoignages en JSON', verbose_name='Couleurs Témoignages (JSON)'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='testimonials_description',
            field=models.TextField(default='Découvrez les retours de nos clients satisfaits', max_length=500, verbose_name='Description section Témoignages'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='testimonials_title',
            field=models.CharField(default='Ce que disent nos clients', max_length=200, verbose_name='Titre section Témoignages'),
        ),
    ]
