# Generated by Django 6.0.3 on 2026-05-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0011_sitecustomization_blog_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecustomization',
            name='show_slideshow',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='slideshow_autoplay_delay',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='slideshow_colors',
        ),
        migrations.AddField(
            model_name='slide',
            name='slideshow_autoplay_delay',
            field=models.PositiveIntegerField(default=3500, help_text='Délai entre les slides en millisecondes', verbose_name='Délai autoplay (ms)'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slideshow_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration des couleurs du diaporama en JSON', verbose_name='Couleurs Diaporama (JSON)'),
        ),
    ]
