# Generated by Django 6.0.3 on 2026-05-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0012_remove_sitecustomization_show_slideshow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slideshow_background_color',
            field=models.CharField(default='rgba(0, 0, 0, 0.4)', help_text='Couleur de fond du contenu (ex: rgba(0, 0, 0, 0.4))', max_length=50, verbose_name='Couleur fond contenu'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slideshow_overlay_color',
            field=models.CharField(default='rgba(0, 0, 0, 0.7)', help_text="Couleur de l'overlay (ex: rgba(0, 0, 0, 0.7))", max_length=50, verbose_name='Couleur overlay'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slideshow_subtitle_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur du sous-titre du slide (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur sous-titre'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slideshow_title_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur du titre du slide (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur titre'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slideshow_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration avancée des couleurs du diaporama en JSON (optionnel)', verbose_name='Couleurs avancées (JSON - optionnel)'),
        ),
    ]
