# Generated by Django 6.0.3 on 2026-05-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0013_slide_slideshow_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_badge_background_color',
            field=models.CharField(default='#F59E0B', help_text='Couleur de fond des badges (format hex: #F59E0B)', max_length=7, verbose_name='Couleur fond badges'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_badge_text_color',
            field=models.CharField(default='#1F2937', help_text='Couleur du texte des badges (format hex: #1F2937)', max_length=7, verbose_name='Couleur texte badges'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_button_border_color',
            field=models.CharField(default='#1e3a5f', help_text='Couleur de bordure du bouton secondaire (format hex: #1e3a5f)', max_length=7, verbose_name='Couleur bordure bouton secondaire'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_button_primary_color',
            field=models.CharField(default='#1e3a5f', help_text='Couleur de fond du bouton principal (format hex: #1e3a5f)', max_length=7, verbose_name='Couleur fond bouton principal'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_button_primary_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur du texte du bouton principal (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur texte bouton principal'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_button_secondary_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond du bouton secondaire (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur fond bouton secondaire'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_button_secondary_text_color',
            field=models.CharField(default='#1e3a5f', help_text='Couleur du texte du bouton secondaire (format hex: #1e3a5f)', max_length=7, verbose_name='Couleur texte bouton secondaire'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond des cartes (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur fond cartes'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_border_color',
            field=models.CharField(default='#3B82F6', help_text='Couleur de bordure des cartes (format hex: #3B82F6)', max_length=7, verbose_name='Couleur bordure cartes'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_title_color',
            field=models.CharField(default='#9CA3AF', help_text='Couleur des titres des cartes (format hex: #9CA3AF)', max_length=7, verbose_name='Couleur titre cartes'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_card_value_color',
            field=models.CharField(default='#1F2937', help_text='Couleur des valeurs des cartes (format hex: #1F2937)', max_length=7, verbose_name='Couleur valeur cartes'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_subtitle_color',
            field=models.CharField(default='#6B7280', help_text='Couleur du sous-titre (format hex: #6B7280)', max_length=7, verbose_name='Couleur sous-titre'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_title_color',
            field=models.CharField(default='#1F2937', help_text='Couleur du titre principal (format hex: #1F2937)', max_length=7, verbose_name='Couleur titre principal'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='hero_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration avancée des couleurs de la section Hero en JSON (optionnel)', verbose_name='Couleurs avancées (JSON - optionnel)'),
        ),
    ]
