# Generated by Django 6.0.3 on 2026-05-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0014_sitecustomization_hero_badge_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='services_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond de la section (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur fond'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='services_card_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond des cartes de services (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur fond cartes'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='services_card_description_color',
            field=models.CharField(default='#6B7280', help_text='Couleur des descriptions des cartes (format hex: #6B7280)', max_length=7, verbose_name='Couleur description cartes'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='services_card_title_color',
            field=models.CharField(default='#1F2937', help_text='Couleur des titres des cartes (format hex: #1F2937)', max_length=7, verbose_name='Couleur titre cartes'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='services_description_color',
            field=models.CharField(default='#6B7280', help_text='Couleur de la description (format hex: #6B7280)', max_length=7, verbose_name='Couleur description'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='services_title_color',
            field=models.CharField(default='#1F2937', help_text='Couleur du titre de la section (format hex: #1F2937)', max_length=7, verbose_name='Couleur titre'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='services_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration avancée des couleurs de la section Services en JSON (optionnel)', verbose_name='Couleurs avancées (JSON - optionnel)'),
        ),
    ]
