# Generated by Django 6.0.3 on 2026-05-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0015_sitecustomization_services_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='customization/hero/', verbose_name='Image Hero (côté droit)'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_image_badge_color',
            field=models.CharField(default='#1E3A8A', help_text='Couleur de fond du badge (format hex: #1E3A8A)', max_length=7, verbose_name='Couleur fond badge'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_image_badge_description',
            field=models.CharField(default='Langue française • Présentations • Coaching', max_length=300, verbose_name='Description sous le badge'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_image_badge_icon',
            field=models.ImageField(blank=True, null=True, upload_to='customization/hero/', verbose_name='Icône du badge (optionnel)'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_image_badge_text',
            field=models.CharField(default='Conseil & accompagnement', max_length=200, verbose_name="Texte badge sur l'image"),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='hero_image_badge_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur du texte du badge (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur texte badge'),
        ),
    ]
