# Generated by Django 6.0.3 on 2026-05-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0016_sitecustomization_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='about_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond de la section (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur fond'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='about_card_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond de la carte (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur fond carte'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='about_description_color',
            field=models.CharField(default='#6B7280', help_text='Couleur de la description (format hex: #6B7280)', max_length=7, verbose_name='Couleur description'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='about_title_color',
            field=models.CharField(default='#1F2937', help_text='Couleur du titre (format hex: #1F2937)', max_length=7, verbose_name='Couleur titre'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='show_about_section',
            field=models.BooleanField(default=True, verbose_name='Afficher la section À propos'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='about_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration avancée des couleurs de la section À propos en JSON (optionnel)', verbose_name='Couleurs avancées (JSON - optionnel)'),
        ),
    ]
