# Generated by Django 6.0.3 on 2026-05-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0017_sitecustomization_about_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='cta_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond de la carte CTA (ex: #FFFFFF)', max_length=7, verbose_name='Couleur fond CTA'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='cta_button_primary_color',
            field=models.CharField(default='#1E40AF', help_text='Couleur du bouton principal CTA (ex: #1E40AF)', max_length=7, verbose_name='Couleur bouton principal CTA'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='cta_button_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur du texte du bouton CTA (ex: #FFFFFF)', max_length=7, verbose_name='Couleur texte bouton CTA'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='cta_description_color',
            field=models.CharField(default='#6B7280', help_text='Couleur de la description CTA (ex: #6B7280)', max_length=7, verbose_name='Couleur description CTA'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='cta_title_color',
            field=models.CharField(default='#1F2937', help_text='Couleur du titre CTA (ex: #1F2937)', max_length=7, verbose_name='Couleur titre CTA'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='show_cta_section',
            field=models.BooleanField(default=True, verbose_name="Afficher la section CTA sur la page d'accueil"),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='cta_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration avancée des couleurs de la section CTA en JSON', verbose_name='Couleurs CTA avancées (JSON)'),
        ),
    ]
