# Generated by Django 6.0.3 on 2026-05-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0018_add_cta_color_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='blog_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond de la section Blog (ex: #FFFFFF)', max_length=7, verbose_name='Couleur fond Blog'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='blog_border_color',
            field=models.CharField(default='#E5E7EB', help_text='Couleur de bordure des cartes articles (ex: #E5E7EB)', max_length=7, verbose_name='Couleur bordure carte article'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='blog_card_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond des cartes articles (ex: #FFFFFF)', max_length=7, verbose_name='Couleur fond carte article'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='blog_description_color',
            field=models.CharField(default='#6B7280', help_text='Couleur de la description Blog (ex: #6B7280)', max_length=7, verbose_name='Couleur description Blog'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='blog_title_color',
            field=models.CharField(default='#1F2937', help_text='Couleur du titre Blog (ex: #1F2937)', max_length=7, verbose_name='Couleur titre Blog'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='partners_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond de la section Partenaires (ex: #FFFFFF)', max_length=7, verbose_name='Couleur fond Partenaires'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='partners_border_color',
            field=models.CharField(default='#E5E7EB', help_text='Couleur de bordure des cartes partenaires (ex: #E5E7EB)', max_length=7, verbose_name='Couleur bordure carte partenaire'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='partners_card_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond des cartes partenaires (ex: #FFFFFF)', max_length=7, verbose_name='Couleur fond carte partenaire'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='partners_title_color',
            field=models.CharField(default='#1F2937', help_text='Couleur du titre Partenaires (ex: #1F2937)', max_length=7, verbose_name='Couleur titre Partenaires'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='testimonials_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond de la section Témoignages (ex: #FFFFFF)', max_length=7, verbose_name='Couleur fond Témoignages'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='testimonials_border_color',
            field=models.CharField(default='#E5E7EB', help_text='Couleur de bordure des cartes témoignages (ex: #E5E7EB)', max_length=7, verbose_name='Couleur bordure carte témoignage'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='testimonials_card_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond des cartes témoignages (ex: #FFFFFF)', max_length=7, verbose_name='Couleur fond carte témoignage'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='testimonials_description_color',
            field=models.CharField(default='#6B7280', help_text='Couleur de la description Témoignages (ex: #6B7280)', max_length=7, verbose_name='Couleur description Témoignages'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='testimonials_title_color',
            field=models.CharField(default='#1F2937', help_text='Couleur du titre Témoignages (ex: #1F2937)', max_length=7, verbose_name='Couleur titre Témoignages'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='blog_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration avancée des couleurs de la section Blog en JSON', verbose_name='Couleurs Blog avancées (JSON)'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='partners_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration avancée des couleurs de la section Partenaires en JSON', verbose_name='Couleurs Partenaires avancées (JSON)'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='testimonials_colors',
            field=models.TextField(blank=True, default='{}', help_text='Configuration avancée des couleurs de la section Témoignages en JSON', verbose_name='Couleurs Témoignages avancées (JSON)'),
        ),
    ]
