# Generated by Django 6.0.5 on 2026-05-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0019_add_sections_color_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='testimonials_image',
            field=models.ImageField(blank=True, null=True, upload_to='customization/testimonials/', verbose_name='Image section Témoignages'),
        ),
    ]
