# Generated by Django 6.0.3 on 2026-05-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0020_sitecustomization_testimonials_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slide_background_color',
            field=models.CharField(default='#FFFFFF', help_text="Couleur de fond de secours si pas d'image (format hex: #FFFFFF)", max_length=7, verbose_name='Couleur de fond'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_content_background_color',
            field=models.CharField(default='rgba(0, 0, 0, 0.4)', help_text='Couleur de fond du conteneur de texte (ex: rgba(0, 0, 0, 0.4))', max_length=50, verbose_name='Couleur fond contenu'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_content_border_color',
            field=models.CharField(default='#3B82F6', help_text='Couleur de bordure du conteneur de texte (format hex: #3B82F6)', max_length=7, verbose_name='Couleur de bordure'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_content_border_radius',
            field=models.PositiveIntegerField(default=16, help_text='Rayon de.border arrondi en pixels', verbose_name='Border radius (px)'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_content_padding',
            field=models.PositiveIntegerField(default=24, help_text='Padding du conteneur de texte en pixels', verbose_name='Padding (px)'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_overlay_color',
            field=models.CharField(default='rgba(0, 0, 0, 0.7)', help_text="Couleur de l'overlay sur l'image (ex: rgba(0, 0, 0, 0.7))", max_length=50, verbose_name="Couleur de l'overlay"),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_show_border',
            field=models.BooleanField(default=False, verbose_name='Afficher la bordure'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_subtitle_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur du sous-titre du slide (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur du sous-titre'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_title_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur du titre du slide (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur du titre'),
        ),
    ]
