# Generated by Django 6.0.3 on 2026-05-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0021_slide_slide_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slide_badge_color',
            field=models.CharField(default='#3B82F6', help_text='Couleur de fond du badge (format hex: #3B82F6)', max_length=7, verbose_name='Couleur du badge'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_badge_text',
            field=models.CharField(blank=True, default='', help_text='Texte du badge/étiquette du slide', max_length=100, verbose_name='Texte du badge'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_button_color',
            field=models.CharField(default='#1E40AF', help_text='Couleur de fond du bouton (format hex: #1E40AF)', max_length=7, verbose_name='Couleur du bouton'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_button_link',
            field=models.CharField(blank=True, default='', help_text="Lien du bouton d'action", max_length=200, verbose_name='Lien du bouton'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_button_text',
            field=models.CharField(blank=True, default='', help_text="Texte du bouton d'action", max_length=100, verbose_name='Texte du bouton'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_button_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur du texte du bouton (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur texte bouton'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_content_text',
            field=models.TextField(blank=True, help_text='Texte de contenu principal du slide', max_length=1000, verbose_name='Texte de contenu'),
        ),
    ]
