# Generated by Django 6.0.5 on 2026-05-24 16:53

import utilitaire.r2_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0022_slide_slide_badge_color_slide_slide_badge_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecustomization',
            name='about_image',
            field=models.ImageField(blank=True, null=True, storage=utilitaire.r2_storage.R2PublicMediaStorage(), upload_to='customization/about/', verbose_name='Image section À propos'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, storage=utilitaire.r2_storage.R2PublicMediaStorage(), upload_to='customization/hero/', verbose_name='Image de fond Hero'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, storage=utilitaire.r2_storage.R2PublicMediaStorage(), upload_to='customization/hero/', verbose_name='Image Hero (côté droit)'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='hero_image_badge_icon',
            field=models.ImageField(blank=True, null=True, storage=utilitaire.r2_storage.R2PublicMediaStorage(), upload_to='customization/hero/', verbose_name='Icône du badge (optionnel)'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='testimonials_image',
            field=models.ImageField(blank=True, null=True, storage=utilitaire.r2_storage.R2PublicMediaStorage(), upload_to='customization/testimonials/', verbose_name='Image section Témoignages'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(storage=utilitaire.r2_storage.R2PublicMediaStorage(), upload_to='slides/', verbose_name='Image du slide'),
        ),
    ]
