# Generated by Django 6.0.5 on 2026-05-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond de la carte (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur fond carte'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_category_color',
            field=models.CharField(default='#3B82F6', help_text='Couleur de la catégorie (format hex: #3B82F6)', max_length=7, verbose_name='Couleur catégorie'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_category_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur du texte de la catégorie (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur texte catégorie'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_description_color',
            field=models.CharField(default='#6B7280', help_text='Couleur de la description (format hex: #6B7280)', max_length=7, verbose_name='Couleur description'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_title_color',
            field=models.CharField(default='#1F2937', help_text='Couleur du titre (format hex: #1F2937)', max_length=7, verbose_name='Couleur titre'),
        ),
    ]
