# Generated by Django 6.0.5 on 2026-05-24 16:53

import utilitaire.r2_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_service_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=utilitaire.r2_storage.R2PublicMediaStorage(), upload_to='services/', verbose_name='Image du service'),
        ),
    ]
