# Generated by Django 6.0.3 on 2026-05-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_card_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur de fond de la carte article (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur fond carte'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_excerpt_color',
            field=models.CharField(default='#6B7280', help_text="Couleur de l'extrait (format hex: #6B7280)", max_length=7, verbose_name='Couleur extrait'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_tag_background_color',
            field=models.CharField(default='#3B82F6', help_text='Couleur de fond des tags (format hex: #3B82F6)', max_length=7, verbose_name='Couleur fond tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_tag_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Couleur du texte des tags (format hex: #FFFFFF)', max_length=7, verbose_name='Couleur texte tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_title_color',
            field=models.CharField(default='#1F2937', help_text='Couleur du titre (format hex: #1F2937)', max_length=7, verbose_name='Couleur titre'),
        ),
    ]
