# Generated by Django 6.0.5 on 2026-05-24 16:53

import utilitaire.r2_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_article_card_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, storage=utilitaire.r2_storage.R2PublicMediaStorage(), upload_to='articles/', verbose_name='Image principale'),
        ),
    ]
