# Generated by Django 6.0.5 on 2026-05-24 16:53

import utilitaire.r2_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='logo',
            field=models.ImageField(storage=utilitaire.r2_storage.R2PublicMediaStorage(), upload_to='partenaires/', verbose_name='Logo'),
        ),
    ]
